# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

resolver: lts-9.17

# User packages to be built.
packages:
- location: sys/sort

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:

# Override default flag values for local packages and extra-deps
flags: 

# Extra package databases containing global packages
extra-package-dbs: []

# Override the architecture used by stack, especially useful on Windows
arch: x86_64
